name: Deploy Hash Studio to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: web-hash-studio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Prepare standalone output
        run: |
          mkdir -p output
          cp -r .next/standalone/* output/
          cp -r .next/static output/.next/static
          cp -r public output/public
          cp package.json output/
          cp -r node_modules output/node_modules || true

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: output

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: .
